print("Program starting.")
Brand = input("Insert car brand: ")
Model = input("Insert car model: ")
print(f"Car brand is \"{Brand}\" ", end="")
print("and the model is ", f"{Model}'", sep="'")
print("Program ending.") 